apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-link-walker-kotlin
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-link-walker-kotlin
    app.kubernetes.io/instance: fint-link-walker-kotlin_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-link-walker-kotlin:latest
  kafka:
    enabled: true
    acls:
      - topic: '*fint-customer-objects.client*'
        permission: admin
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m